### ISSUE TITLE
Discrepancy between Doumith and lissero

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [MDU-PHL/LisSero#4]
I have create the following table to show how LisSero interprets a certain combination of amplicons, compared to the paper of Doumith. As you can see, LisSero assigns the serotype to a lot of combinations that do not appear in the Doumith paper. I was wondering if this classification is documented somewhere, is it from another publication?

gene combinations|doumith|lissero
-----------------|-------|-------
Prs|?4a,4c|?4a,4c
ORF2110|?|4b,4d,4e
ORF2110,Prs|?|4b,4d,4e
ORF2819|1/2b,3b,7|1/2b,3b,7
ORF2819,Prs|1/2b,3b,7|1/2b,3b,7
ORF2819,ORF2110|4b,4d,4e|4b,4d,4e
ORF2819,ORF2110,Prs|4b,4d,4e|4b,4d,4e
lmo0737|1/2a,3a|1/2a,3a
lmo0737,Prs|1/2a,3a|1/2a,3a
lmo0737,ORF2110|?|4b,4d,4e
lmo0737,ORF2110,Prs|?|4b,4d,4e
lmo0737,ORF2819|?|4b,4d,4e
lmo0737,ORF2819,Prs|?|4b,4d,4e
lmo0737,ORF2110,ORF2819|?|4b,4d,4e
lmo0737,ORF2110,ORF2819,Prs|?|4b,4d,4e
lmo1118,Prs|?|1/2c,3c
lmo1118,ORF2110|?|1/2c,3c
lmo1118,lmo0737|1/2c,3c|1/2c,3c
lmo1118,lmo0737,Prs|1/2c,3c|1/2c,3c

**Comment by tseemann** [comment]
@Redmar-van-den-Berg thank you for the thorough report. we will investigate and get back to you.

Doumith 2014: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC497638/

**Comment by Redmar-van-den-Berg** [comment]
Hi, has anyone had a chance to look at the differences in the assigned serotypes between Doumith and LisSero?

**Comment by kwongj** [comment]
@Redmar-van-den-Berg Thanks for raising this and apologies for not replying earlier.

The discrepancies came about during some of our testing, when I found some sequences with low depth of coverage didn't always assemble well enough, and subsequently, some genes were not detected in the assemblies. These sequences were assigned to the most likely result e.g. a sequence that had only ORF2110 and Prs detected would be assigned to 4b,4d,4e, as there would not be another serogroup with this combination. Similarly, lmo1118 alone would correspond to 1/2c,3c. For the situations that this was encountered, these predictions were correct.

However, we would be interested to hear if you have encountered any situations where this approach was not correct.

We are planning to rewrite the code, and we have since implemented minimum QC metrics for our sequencing, so this will likely change in the next version - possibly to adding a `?` to the predicted serogroup for those cases.

**Comment by Redmar-van-den-Berg** [comment]
@kwongj Thanks for your reply.

So far, I've only noticed the discrepancy between LisSero and Doumith, and haven't had time to investigate whether assembly missed some genes in those cases.

I'm about to test two different methods to serotype listeria (Assembly + LisSero, and an srst2 based method) on a big public data set, and I will let you know if I encounter any problems with the predictions as you have explained them.

**Comment by Redmar-van-den-Berg** [comment]
I have completed our comparison and attached the [results](https://github.com/MDU-PHL/LisSero/files/1796249/srst2_LisSero_kwong.xlsx). I have compared three different methods to determine the serogroups for the listeria isolates from the [Kwong](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4733179/) study.

First, I used srst2 to detect the genes, and the LisSero scheme to assign the serogroups.
Second, I used srst2 to detect the genes, and used the Doumith scheme to assign the serogroup.
Third, I used abyss to assemble the reads with kmer=31, and LisSero to detect the genes and assign the serotypes.

The conclusion is that there is no difference in using the LisSero or Doumith scheme when using srst2. Using srst2 does perform better then assembly+LisSero, probably because srst2 performs better with low coverage. Also, I did not attempt to optimise the kmer size we used for assembly.

**Comment by kwongj** [comment]
@Redmar-van-den-Berg Thanks for the testing and update! We have been looking at a couple of different assemblers, including the NCBI assembler `skesa`, but it is quite possible that using a read alignment approach is better than assembly.

Just wondering - did you happen to test it on another dataset other than the JCM paper? I'm curious to know if the assumptions I made cause problems in other datasets.

**Comment by Redmar-van-den-Berg** [comment]
@kwongj We only tested our workflows on the Kwong paper. We are currently using the srst2 based approach in our routine surveillance, but I'd be interested in testing the new version on our data once it comes out.
